services:
  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
      - '--web.listen-address=:9200'
    network_mode: host
    pid: host
    restart: always
    volumes:
      - '/:/host:ro,rslave'
  
  # prometheus:
  #   image: prom/prometheus
  #   container_name: prometheus
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #   ports:
  #     - 9090:9090
  #   restart: unless-stopped
  #   volumes:
  #     - ./prometheus:/etc/prometheus
  #     - prom_data:/prometheus
  
  # grafana:
    # image: grafana/grafana
    # container_name: grafana
    # ports:
    #   - 3000:3000
    # restart: unless-stopped
    # environment:
    #   - GF_SECURITY_ADMIN_USER=guille
    #   - GF_SECURITY_ADMIN_PASSWORD=5914
    #   # - GF_AUTH_DISABLE_LOGIN_FORM=true
    #   - GF_AUTH_ANONYMOUS_ENABLED=true
    #   - GF_AUTH_ORG_ROLE=Editor
    # volumes:
    #   - ./grafana:/etc/grafana/provisioning/datasources
    #   - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
# volumes:
#   prom_data: